### ISSUE TITLE
Validation check prevents snapshotting entire pools

### ISSUE THREAD

**Issue by s-burris** [Inner-Heaven/libzetta-rs#172]
If I try to take a snapshot of a pool, e.g.
```Rust
let engine = DelegatingZfsEngine::new().unwrap();
engine.snapshot(&[PathBuf::from("tank@snap")]);
```

then I would get an error such as this: `ValidationErrors([MissingPool("tank@snap")])` due to the following check:
https://github.com/Inner-Heaven/libzetta-rs/blob/708bfd65d640a1e1aa104c7d9f78567636679494/src/zfs/mod.rs#L316

`dataset.components().count()` will be 1. 

I think snapshotting an entire pool is a perfectly reasonable action, but at the very least I believe this warrants a separate error besides `MissingPool` when the pool is supplied.

Removing the second half of that check allows me to snapshot the pool successfully

**Comment by andoriyu** [comment]
@s-burris TIL: I wasn't aware that you can do that until now. If it's just `|| dataset.components().count() < 2` that causes the issue, then we can remove it.
