### ISSUE TITLE
Disk.path() does not return a full relative path on Linux

### ISSUE THREAD

**Issue by s-burris** [Inner-Heaven/libzetta-rs#194]
**Describe the bug**
[Disk.path()](https://docs.rs/libzetta/latest/libzetta/zpool/vdev/struct.Disk.html#method.path) returns the name of a disk pseudofile on Linux, but not a relative path.

Example: if I have a disk `/dev/disk/by-id/wwn-xxxxxxxxxxx` and call `Disk.path()` upon it, the function does not return `disk/by-id/wwn-xxxxxxxxxxx` (which would be the disk's path "relative to /dev/" as the docs say), but rather the pseudofile name on its own `wwn-xxxxxxxxxxx`.

From what I can tell, the root cause is the assumption that the `/dev/` directory does not contain any subdirectories of disks (such as `/dev/disk/by-id` which is only true on BSDs [_by default_](https://rubenerd.com/enabling-dev-diskid-and-dev-gpt-on-freebsd/), but not Linux)

**To Reproduce**
On a Linux machine, create a pool using WWN and `sdX` disk paths:
```sh
 sudo zpool create P01 mirror /dev/sdf /dev/disk/by-id/wwn-0x6000c2915defaf6bbc84aebea038861e
```
Then you can see both devices in `zpool status`:
```sh
$ sudo zpool status
  pool: P01
 state: ONLINE
config:

        NAME                                        STATE     READ WRITE CKSUM
        P01                                         ONLINE       0     0     0
          mirror-0                                  ONLINE       0     0     0
            sdf                                     ONLINE       0     0     0
            wwn-0x6000c2915defaf6bbc84aebea038861e  ONLINE       0     0     0

errors: No known data errors
```
With `-P` to show full paths:
```sh
$ sudo zpool status -P
  pool: P01
 state: ONLINE
config:

        NAME                                                              STATE     READ WRITE CKSUM
        P01                                                               ONLINE       0     0     0
          mirror-0                                                        ONLINE       0     0     0
            /dev/sdf1                                                     ONLINE       0     0     0
            /dev/disk/by-id/wwn-0x6000c2915defaf6bbc84aebea038861e-part1  ONLINE       0     0     0
```
Now, running a short libzetta program:
```Rust
use libzetta::zpool::ZpoolEngine;
use libzetta::zpool::ZpoolOpen3;

fn main() {
    let engine = ZpoolOpen3::default();
    let p01 = engine.status("P01").expect("Could not get P01 status");

    for vdev in p01.vdevs() {
        for disk in vdev.disks() {
            println!("{:?}", disk.path())
        }
    }
}
```
We see that what is returned is not a `path relative to /dev` but only the filename. This is a problem for my uses because to actually get a path, I would have to search child directories of `/dev` for each disk, which is impractical when dealing with large pools. Not to mention, I can't relate differing paths to the same disk in a multipathed environment (important when some go AWOL)
```
"sdf"
"wwn-0x6000c2915defaf6bbc84aebea038861e"
```

**Possible fix**
Note that `/dev/disk/by-id/wwn-0x6000c2915defaf6bbc84aebea038861e-part1` is a symlink to `/dev/sda1`:
```sh
$ ls -lah /dev/disk/by-id/ | grep 38861e
lrwxrwxrwx 1 root root    9 May 12 09:49 scsi-36000c2915defaf6bbc84aebea038861e -> ../../sda
lrwxrwxrwx 1 root root   10 May 12 09:49 scsi-36000c2915defaf6bbc84aebea038861e-part1 -> ../../sda1
```
To get zpool status to show these symlinks resolved, we can use the `-L` flag additionally:
```sh
$ sudo zpool status -PL
  pool: P01
 state: ONLINE
config:

        NAME           STATE     READ WRITE CKSUM
        P01            ONLINE       0     0     0
          mirror-0     ONLINE       0     0     0
            /dev/sdf1  ONLINE       0     0     0
            /dev/sda1  ONLINE       0     0     0
```
I'm not sure how `zpool-status` is called in libzetta, but adding `-L` might sidestep this issue.

**Expected behavior**
From the docs:
> Path to a backing device or file. If path is relative, then it’s relative to /dev/.

I would prefer having an absolute path to the disk no matter what, but returning a path relative to `/dev/` on Linux (e.g. starts with `/disk/by-id/`) would also be a solution.

**Please complete the following information:**
 - OS: Debian bullseye
 - ZFS version: 2.1.7
 - libZetta version 0.4.2

**Comment by andoriyu** [comment]
@s-burris thanks for the report.

It's actually not even true on FreeBSD:
```

[andoriyu@fulcrum /eden/mess/nzb/dst/Other]$ sudo zpool status -P
  pool: eden
 state: ONLINE
  scan: scrub repaired 1M in 15:03:34 with 0 errors on Sat Mar  4 01:12:20 2023
config:

        NAME                           STATE     READ WRITE CKSUM
        eden                           ONLINE       0     0     0
          raidz2-0                     ONLINE       0     0     0
            /dev/diskid/DISK-ZCT2K2R6  ONLINE       0     0     0
            /dev/diskid/DISK-ZCT2QVET  ONLINE       0     0     0
            /dev/diskid/DISK-WSD6B5L6  ONLINE       0     0     0
            /dev/diskid/DISK-ZCT2QWL9  ONLINE       0     0     0
            /dev/diskid/DISK-ZCT2QXEL  ONLINE       0     0     0
            /dev/diskid/DISK-ZCT2RH0W  ONLINE       0     0     0
```

It's probably better to show paths that the user used to create zpool (i.e. symlink in `diskid` in the case above).

Should be an easy fix.

**Comment by s-burris** [comment]
Oh interesting, is `kern.geom.label.disk_ident.enable="1"` by default now?

**Comment by andoriyu** [comment]
> Oh interesting, is `kern.geom.label.disk_ident.enable="1"` by default now?

@s-burris I don't see it explicitly enabled anywhere on my machine, so probably it's a default now.

**Comment by andoriyu** [comment]
Closed in #195

**Comment by s-burris** [comment]
Awesome, thank you for the quick response.

I did find some unexpected behavior related to this, full paths will or not will be returned seemingly based on method of getting pool:
```Rust
use libzetta::zpool::ZpoolEngine;
use libzetta::zpool::ZpoolOpen3;

fn main() {
    let engine = ZpoolOpen3::default();
    let p01 = engine.status("P01").expect("Could not get P01 status");

    println!("With engine.status():");
    for vdev in p01.vdevs() {
        for disk in vdev.disks() {
            println!("{:?}", disk.path())
        }
    }

    println!("With engine.all():");
    for pool in engine.all().unwrap() {
        for vdev in pool.vdevs() {
            for disk in vdev.disks() {
                println!("{:?}", disk.path())
            }
        }
    }
}
```
yields

```
With engine.status():                   
"/dev/disk/by-id/wwn-0x5000cca2c28402f4"
"/dev/disk/by-id/wwn-0x5000cca2c284f08c"
"/dev/disk/by-id/wwn-0x5000cca2c21fdf08"
"/dev/disk/by-id/wwn-0x5000cca2c26db028"
...
With engine.all():
"wwn-0x5000cca2c28402f4"
"wwn-0x5000cca2c284f08c"
"wwn-0x5000cca2c21fdf08"
"wwn-0x5000cca2c26db028"
...
```

I couldn't figure out why this is the case

**Comment by andoriyu** [comment]
`engine.all` and `engine.status` both use `zpool status` but call it with different parameters. There is `engine.status_all` that allows you to pass parameters.

I will change it, so there is only `status` and `status_all` and both will take extra parameter. That will be a breaking change though.
